### ISSUE TITLE
Avatar path in settings

### ISSUE THREAD

**Issue by Kaik** [zikula-modules/Profile#100]
I will use this issue with my problem - when path is set in settings it has to be global 
https://github.com/zikula-modules/Profile/blob/master/Controller/ConfigController.php#L86
while in https://github.com/zikula-modules/Profile/blob/master/Bridge/ProfileModuleBridge.php#L140
it is used as relative path to base path.

Unless you have any other ideas this works 
https://github.com/zikula-modules/Profile/blob/master/Controller/ConfigController.php#L85
```
$path = substr(dirname(__FILE__), 0, strpos(dirname(__FILE__), 'modules')).$modVars[ProfileConstant::MODVAR_AVATAR_IMAGE_PATH];
```
Hmm now I'm not sure if this ticket is a right place for issue.

**Comment by Guite** [comment]
@Kaik can you please check if this is still an issue using the current code base... I would estimate this problem is already gone.

**Comment by Kaik** [comment]
Hi @Guite
