### ISSUE TITLE
User search and edit profile data for admins

### ISSUE THREAD

**Issue by Kaik** [zikula-modules/Profile#115]
So, I do not like to delete users but ban them (via permissions), then they cannot use same email address to register new account and if they are willing to behave I'm able to give them a chance, but sometimes they add stupid stuff in their profile like naked girls in avatars etc... and I have to use PhpMyAdmin to change those fields.

Would be great if you could search user by uname, email or uid and then edit all userdata he has from admin view.

**Comment by Guite** [comment]
> Would be great if you could search user by uname, email or uid and then edit all userdata he has from admin view.

This is already possible, because Profile integrates itself into the Users administration. What is missing?

**Comment by Guite** [comment]
![Screenshot_20200120_081843](https://user-images.githubusercontent.com/277531/72706111-7ccc9100-3b5d-11ea-960b-fbd714b0a649.png)

**Comment by Kaik** [comment]
hmm I guess I have removed it for some reason then... wonder why... let me check it then...

**Comment by Kaik** [comment]
@Guite ok now I see why I had to disable that listener. So the problem is that all those fields are shown both in admin view user edit and on registration form... and the reason I didn't want them to appear there is because translation didn't work.
I use old 2x Zikula old profile module (2018) I have just checked and looks like you fixed it in nov 2018 here https://github.com/zikula-modules/Profile/commit/d1e0950243c3a71880786cc1206219cffee38599

ok, so... hmm it is all messed up... imho Despite the fact that translation works now.
1. Both views should be separated 
2. There should be, a way to hide all those fields from registration form anyway... or even chose fields that are displayed and where...
3. I think hooks are better for this*
*hooks with hook settings

I'm going to write here how I see it, maybe someday I will do PR like this it is just an idea. (I might need to copy it to a separate issue and close this one let me know)
So.. since I removed all those fields from registration form I do like how clean it is, and I will not go back.

Actually now I think that registration form should be as clean as possible and additional data can be collected later, after login, similarly as it is done on facebook or other platforms. So small decentralised questions/links(ajax components etc) like  "Update your age here ", Change avatar (somewhere next to avatar), Which city you are living?... could be in blocks or something. Click, update one bit, and that is it... 
of course somewhere there full profile edit page as well as admin profile edit page (the way it looks/work on the image above is ok)

I know it is feature I do not expect anyone to code above or something it's just a loose concept.

I see it as hook provider (the problem with hooks is that there is no common settings practice/support and hooks providers should have one).
Profile edit hook provider
3 areas 
profile edit area
admin user edit area
registration form area
So basically the only way those fields are editable is via hook provider no direct edit...

Apart from that in that profile edit hook provider in settings, admin can chose fields that are displayed.

So when admin does not want these fields in registration form then hook provider is not attached. If he wants then he can add all of the fields there or chose which he wants to display. Same for other areas. I guess in admin it is better to chose to show all fields anyway, but in edit your profile form in user account not necessarily...

Like I said it is just idea... I think I should split it to a new ticked... let me know if you want this as a new issue and what you think.

**Comment by Guite** [comment]
It **is** a hook provider.
Yes, please put the feature request into a new, clean ticket.

An easy first step would be to add a dropdown checklist to properties allowing to choose none, one or multiple from:

- Shown in admin area
- Shown in registration
- Shown in profile display
- Shown in profile editing
