### ISSUE TITLE
Lists or Field Types Timezone, Country, Language, Currency are not populated

### ISSUE THREAD

**Issue by ThiloWitt** [zikula-modules/Profile#125]
Profile 3.1.17 / Zikula 3.0.3

Sample HTML code:
`</div><div class="form-group row"><label class="col-form-label col-md-3" for="zikulaprofilemodule_editprofile_dynamicFields_zpmpp:country">Country</label><div class="col-md-9">        <select id="zikulaprofilemodule_editprofile_dynamicFields_zpmpp:country" name="zikulaprofilemodule_editprofile[dynamicFields][zpmpp:country]" class="custom-select form-control"><option value=""></option></select>            </div> `

Sample image:
![grafik](https://user-images.githubusercontent.com/1067830/106477840-e093d480-64a8-11eb-88a2-dee6d1c4cb78.png)

**Comment by Guite** [comment]
Fixed in https://github.com/zikula/core/commit/5690a1be9b0177b04b4733f73a83f866ec7e4b19
