### ISSUE TITLE
Form Validation Needs Better Visualization at the Fields Themselves

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Profile#31]
When the user submits the registration form here:

/index.php?module=users&type=user&func=register

if there are required fields that have not been filled out, then the form only displays this error at the top of the form:

"There was an error with one of the fields, below. Please review the message, and correct your entry."

However, the fields themselves are not displaying anything else visible to alert the user about the specific items that need to be addressed.

The Legal module has the same issue.

**Comment by Guite** [comment]
This needs to wait until the UsersUI listeners can be incorporated into a Symfony form. Postponed to 3.0.0 hence.

**Comment by craigh** [comment]
forms in use now
