### ISSUE TITLE
The textarea form field for "Content" does not get revealed

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Profile#33]
If Select2 is enabled at a site, using this example init code:

$('select').select2({
            'allowClear': true,
            'placeholderOption': 'first',
            'width': 'copy'
        });

Then, the textarea form field for "Content" does not get revealed when selecting "Type of control to display" as "Dropdown list" here:

/index.php?module=profile&type=admin&func=edit

So, it looks like there might be a JavaScript conflict occurring. Although, no error message is output in the JavaScript console.

**Comment by Guite** [comment]
Migration to jQuery done in 60d94d013b9efe2f269872f6c02f999909c529b0

Please note that migration to 2.0-spec is not completed yet (see #58).
