### ISSUE TITLE
Translation instruction is wrong

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Profile#46]
profile 2.0.0 beta in zk 1.4.0

The translation instruction is wrong:

```
Copy all the files of the /modules/Profile/locale directory to /config/locale.
```

These paths are not valid in zk1.4.0

**Comment by craigh** [comment]
@rallek can you provide a PR to fix this? :smile:

**Comment by rallek** [comment]
Might take some days

**Comment by craigh** [comment]
I've changed the paths but I've never used this feature. It technology is pretty bad, IMO and needs to be changed asap, but no time before Core 1.4.0 is out I think. Can someone test and see if the provided method still works at all?

**Comment by rallek** [comment]
I am very limited in time. Let us test this together with translation testing (later). First we would need an core pot file (including twig strings)

**Comment by craigh** [comment]
Twig strings will not happen in 1.4.0

**Comment by Guite** [comment]
What's the state of this issue?

**Comment by craigh** [comment]
unchanged.

**Comment by craigh** [comment]
won't fix
