### ISSUE TITLE
 Date mistakes with new user attribute put in #2071

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/Profile#47]
See details in:
https://github.com/zikula/core/issues/2071

**Comment by Portugao** [comment]
How to handle this?
Make a new version 1.6.2 for Zik 1.3.x?

**Comment by craigh** [comment]
> Make a new version 1.6.2 for Zik 1.3.x?

yes - merge fixes to 1.6 branch and also to master so fixes are reflected in both versions

**Comment by Portugao** [comment]
Maybe a fix is not nessecary for the master branch, because there it is converted to jQuery.

**Comment by Portugao** [comment]
Like expected this issue is not relevant for the master branch. There we have a jQuery datepicker.

**Comment by craigh** [comment]
closed by #48
