### ISSUE TITLE
Placement of Form Validation Messages

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Profile#49]
All forms should have its validation messages placed under the relevant fields, not above the fields. For example, look at the installer form, which places the messages above the fields. It is a better user experience to place the messages below the field, in the event there are many messages associated with a particular field. Otherwise, the fields can potentially get pushed too far down. This should be consistent across all Zikula forms, to place the messages below the fields. If there is any existing "help" text, then the validation messages get placed underneath.

![form-validation](https://cloud.githubusercontent.com/assets/274862/6323128/3432a646-baf2-11e4-829d-496697a026d2.png)

Zikula 1.4.0 build 452

**Comment by craigh** [comment]
why is this in the profile project?

**Comment by craigh** [comment]
and by the way, this is default symfony behavior. maybe the ticket more appropriately should go to the symfony project.

**Comment by cmfcmf** [comment]
I agree with @craigh.

**Comment by shefik** [comment]
@craigh I accidentally posted this ticket in the Profile module, instead of the Zikula core. I'm submitting a pull request to Zikula core, since the issue is with the layout of Zikula templates. It's not an issue with Symfony itself.
