### ISSUE TITLE
Migrate to 2.0 spec

### ISSUE THREAD

**Issue by Guite** [zikula-modules/Profile#58]
- [x] Raise version to 2.1.0
- [x] CS fixes
- [x] Basic adaptions for core 1.4.3
  - [x] Add Zikula manifest file
 - [x] Use composer instead of old version class
 - [x] Use link container
 - [x] Use new installer class
- [x] Use `$this->extensionApi->getModuleInstanceOrNull` as a replacement for `ModUtil::available`
- [x] Users UI listener
- [x] Migrate to Twig
  - [x] Reimplement Smarty plugins as Twig functions
- [x] New controller classes
  - [x] Create dedicated config controller
  - [x] Migrate Ajax, Form, User, Admin
  - [x] Redistribute actions to topic controllers
- [x] Migrate JS to jQuery
- [x] Migrate blocks
- [x] Todo markers
- [x] Move queries into repository class
- [ ] Testing

**Comment by craigh** [comment]
I would like to see the doctrine translatable extension used to replace existing methods of translating the labels please.

**Comment by Guite** [comment]
This is #55
