### ISSUE TITLE
Once Profile is installed admin-panel-menue stops working

### ISSUE THREAD

**Issue by MrMontesa** [zikula-modules/Profile#62]
During testing of [Core issue 3236](https://github.com/zikula/core/issues/3236) & [Content issue 176](https://github.com/zikula-modules/Content/issues/176) I came across a Profile issue.

As soon as you install Profile module the admin-panel-menue stops working and on creating a new user the "set password now" tick does not bring up the 2 password form fields.

This is how to reproduce:
- install build156
- activate profile module
- access: /zauth/admin/user/create in order to create a new user
- click on admin-panel-menue link in header menu: nothing happens
- tick: set password now: password entry form fields do NOT pop up
- click in the admin menu items SysteM/Layout/Users/Uncategorized/etc: no submenue pop out

In Chrome developer toolbar I see 2 alerts:
Uncaught SyntaxError: missing ) after argument list ./theme/combined_asset/js/0084146b504dd81eedaf857f722cffcb1186400.js
&
Uncaught ReferenceError: jQuery is not defined(…)  create:1007

**Comment by Guite** [comment]
Fixed in d872fe1b69bef822f64114a0b5ffe2255f46d141

**Comment by MrMontesa** [comment]
Treid build157 where I can confirm "set password" popup working again. Same for the submenues in admin panel.
But admin-panel-menue does not pop out. Console sais:

`Uncaught TypeError: Failed to construct 'URL': Please use the 'new' operator, this DOM object constructor cannot be called as a function.(…)`

In Firefox all seems to work fine. I cleared the Chrome cache and Zikula cache but no change in behavior.

**Comment by Guite** [comment]
Can you disable the asset merger and check the console to see in which JS file this error occurs?

**Comment by MrMontesa** [comment]
In first place I wasnt able to reproduce this at home on my linux workstation with either Chrome or Firefox. Both do work as expected and show the admin-panel-menu.
Then I used the Windows Laptop and was able to get the same error message as before which is sourced from:

`javascript/js-webshim/dev/polyfiller.js`

Hope this helps.

**Comment by Guite** [comment]
Tracked in https://github.com/zikula/core/issues/3238
