### ISSUE TITLE
'Select' Profile Field Gets Created as 'Text Box'

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Profile#68]
When creating a new Profile field as `Select`, the field gets saved as `Text box` instead.

/profile/admin/edit

**Comment by shefik** [comment]
Form validation should be on the fieldset `Type of control to display` to make it required, since `Select` does mean a `select` form field. Rather, it means to select a choice from the dropdown.

**Comment by craigh** [comment]
won't fix
