### ISSUE TITLE
Form Fields Have Incorrect Name Attributes

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Profile#69]
Previously, form fields were populated similar to `dynadata[user_information_name]` for the attribute `name`. Now, they are being populated as `dynadata[example][user_information_suffix]`. So, the `[example]` array is being set, when it should not be there.

Create a Profile field and view the registration form as an example.

**Comment by craigh** [comment]
why should it not be there? This is likely a result of the way symfony is generating the form. It isn't a bug.

**Comment by Guite** [comment]
DUDs aren't using Sf forms yet.

**Comment by shefik** [comment]
It wasn't there before in the prior release, so this is something new that should be noted somewhere. Otherwise, it can be considered a break in prior release which populated arrays differently.

See line 395 in the file `/modules/zikula/profile-module/Twig/TwigExtension.php`. `[example]` is being set there, so it can be anything, but it is hard-coded to default to `[example]`.

**Comment by shefik** [comment]
I don't really have an issue with the change in the populating the array. It's just that seeing `example` threw me off in the output. Made it seem like it wasn't the real data I was supposed to get. Maybe renaming the default to something else than `example` is better?

**Comment by craigh** [comment]
I disagree that changing the html source code is any kind of a BC break. 

I agree that `example` seems weird.

**Comment by shefik** [comment]
It broke for me, cause I had a listener that loaded JavaScript which was looking for `dynadata[user_information_name]` and not `dynadata[example][user_information_name]`.

**Comment by craigh** [comment]
won't fix
