### ISSUE TITLE
Registration Fails, If Dropdown Form Field Is Required

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Profile#72]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.6

### Expected behavior

New registrations should be successful.

### Actual behavior

A new user is not registered.

### Steps to reproduce

Install the Profile module. Then, go to `/profile/admin/edit/4` and set the Time Zone Offset field to `required`. Then, attempt to register a new account at `/register`.

If you reset the field back to option, then registration is successful.

You can also repeat the error, if you create a `country` dropdown field and make it required.

**Comment by craigh** [comment]
updated profile can be released anytime. doesn't have to wait for core
