### ISSUE TITLE
Profile links from e.g. news are not working like expected

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Profile#73]
I am using latest NewsModule and profile within zikula 1.4.4
If I have a news where the contributor is shown, the contributor is available as a link. For example the link is pointing to ``http://mysite.tld/profile/view?uid=4`` but profile is showing up within the following url: ``http://mysite.tld/profile/profile/display``. In this case myself is showing (the admin). The uid is missing.

**Comment by craigh** [comment]
The redirect is not passing the args

**Comment by rallek** [comment]
Same with a MOST module, if I use the users-field there

**Comment by craigh** [comment]
won't fix
