### ISSUE TITLE
Fatal Error: Two extensions share the same displayname. [ZikulaProfileModule] and []

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Profile#76]
I am getting the following error with Zikula 1.4.5 at `/extensions/module/list`:

`Fatal Error: Two extensions share the same displayname. [ZikulaProfileModule] and []`

Unable to proceed with loading the page.

**Comment by shefik** [comment]
For some reason, the module `ZikulaPermissionsModule` is showing up along with the error.

**Comment by shefik** [comment]
The display name `ZikulaPermissionsModule` for is not being retrieved, and being set as empty:

``Array ( [name] => ZikulaPermissionsModule [type] => 3 [directory] => PermissionsModule [displayname] => [oldnames] => Array ( ) [description] => User permissions manager [version] => 1.2.0 [url] => permissions [capabilities] => a:1:{s:5:"admin";a:1:{s:5:"route";s:39:"zikulapermissionsmodule_permission_list";}} [securityschema] => a:1:{s:25:"ZikulaPermissionsModule::";s:2:"::";} [dependencies] => a:1:{i:0;a:4:{s:7:"modname";s:3:"php";s:10:"minversion";s:6:">5.4.0";s:10:"maxversion";s:6:">5.4.0";s:6:"status";i:1;}} [corecompatibility] => >=1.4.1 [core_max] => )
``

**Comment by shefik** [comment]
Same issue for the `Profile` module. The display name is not being retrieved, and being set as empty:

``Array ( [name] => ZikulaProfileModule [type] => 2 [directory] => zikula/profile-module [displayname] => [oldnames] => Array ( [0] => Profile ) [description] => User profiles and member list [version] => 2.1.0 [url] => profile [capabilities] => a:3:{s:5:"admin";a:1:{s:5:"route";s:33:"zikulaprofilemodule_config_config";}s:4:"user";a:1:{s:5:"route";s:35:"zikulaprofilemodule_profile_display";}s:7:"profile";a:1:{s:7:"version";s:3:"1.0";}} [securityschema] => a:11:{s:21:"ZikulaProfileModule::";s:2:"::";s:25:"ZikulaProfileModule::view";s:2:"::";s:25:"ZikulaProfileModule::item";s:56:"DynamicUserData PropertyName::DynamicUserData PropertyID";s:27:"ZikulaProfileModule:Members";s:2:"::";s:34:"ZikulaProfileModule:Members:recent";s:2:"::";s:34:"ZikulaProfileModule:Members:online";s:2:"::";s:38:"ZikulaProfileModule:FeaturedUserblock:";s:13:"Block title::";s:34:"ZikulaProfileModule:LastSeenblock:";s:13:"Block title::";s:36:"ZikulaProfileModule:LastXUsersblock:";s:13:"Block title::";s:39:"ZikulaProfileModule:MembersOnlineblock:";s:13:"Block title::";s:10:"Userblock:";s:13:"Block title::";} [dependencies] => a:1:{i:0;a:4:{s:7:"modname";s:3:"php";s:10:"minversion";s:6:">5.4.0";s:10:"maxversion";s:6:">5.4.0";s:6:"status";i:1;}} [corecompatibility] => >=1.4.3 [core_max] => )``

@craigh Is this a code issue or a Profile issue. Seems like only the Permissions and Profile module are having this problem?

**Comment by shefik** [comment]
I found the issue. It's due to a translation problem. At line 170, the file `/lib/Zikula/Bundle/CoreBundle/Bundle/MetaData.php` attempts to due a translation on the module's display name (which is indeed initially retrieved correctly).

``return $this->__(/** @Ignore */$this->displayName);``

However, If you have a language translation file, and did not explicitly set a translation for the module's display name, then it returns as empty (because the translation is not return the key, only the value). So this a problem, because I am only using an English translation file, so the assumption is that the display name should have been just return as the key (which is the same display name `Permissions`).

So, the only way I can prevent the error is to update the file `/app/Resources/translations/zikula.en.po` and setting an English translation as `Permissions`, even though the key is already `Permissions`. Same for setting an English translation as `Profile`, even though the key is already `Profile`. This will make the display name populate correctly.

**Comment by craigh** [comment]
change code to

    $display = $this->__(/** @Ignore */$this->displayName);

    return empty($display) ? $this->displayName : $display;

PR appreciated.

**Comment by shefik** [comment]
Ok

**Comment by shefik** [comment]
Refs. https://github.com/zikula/core/pull/3399
