### ISSUE TITLE
Users Module showed untranslated details - Zikula 1.4.6

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/Profile#78]
Hello Developers,

I have an issue with the Users Module. In the front end or when entering the details of a user was not translated. I have the modules version 2.0.0 under Zikula 1.4.6. Here is the screenshot.

![zikula-users-module-issue](https://cloud.githubusercontent.com/assets/7885632/23332798/f8af4f5e-fb7f-11e6-8447-1f2f8d07b852.jpg)

Do I have to adjust something or what needs to be done?

Thanks in advance.

**Comment by rallek** [comment]
[translations.zip](https://github.com/zikula-modules/Profile/files/801338/translations.zip)
did you upload a translation for Pages? Attached my version of translation.

**Comment by AlexL777** [comment]
Something I'm still doing wrong. I have uploaded these .po files to the **/modules/Pages/ Ressources/translations** directory. Unfortunately in the backend under "Seitenliste" is displayed, Key for "de" is nonexistent.

Error message looks like this.

`Key "de" for array with keys "en" does not exist.`

StackTrace looks like this.

`In modules/Pages/Resources/views/Admin/view.html.twig at line 35`

**Comment by rallek** [comment]
we are talking about the ProfileModule in this ticket but your failure is about PagesModule. The language files in my zip are for profile...

**Comment by AlexL777** [comment]
I have changed Zikula to "English", because at Pages it was this error.

Fields in profiles I have also in English not properly named. I'll see how this works. Thank you!
