### ISSUE TITLE
Store user TZ properly

### ISSUE THREAD

**Issue by craigh** [zikula-modules/Profile#79]
refs https://github.com/zikula/core/issues/1144

**Comment by Guite** [comment]
fyi: you can mark a string field as `timezone` in MOST which uses http://symfony.com/doc/current/reference/forms/types/timezone.html

**Comment by craigh** [comment]
Profile needs to dynamically generate all attribute fields, so it cannot be generated via most

**Comment by robbrandt** [comment]
I think @guite is referring to fields in MOST modules that are timezone sensitive, so that the math can be done between the current time and the zone identified in Profile vs the time and zone specified in a MOST module.

**Comment by craigh** [comment]
master now stores TZ data as needed, but on upgrade the data is not properly handled yet. This needs to be done still.

**Comment by craigh** [comment]
upgrade complete.
