### ISSUE TITLE
implement proper avatar handling

### ISSUE THREAD

**Issue by craigh** [zikula-modules/Profile#80]
- [x] Add avatar display method to Profile interface
  - [x] Update places using the old Smarty plugin
    - [x] `system/UsersModule/Controller/LiveSearchController.php`
    - [x] `system/UsersModule/Twig/Extension/ProfileExtension.php`
  - [x] Review/extend modvars (`ProfileConstant` class, still used from Users module)
  - [x] Finish implementation in `ProfileModuleBridge`
- [x] Update avatar display within Profile module
  - [x] Twig extension
  - [x] `Profile/display.html.twig`
  - [x] `Hook/display.html.twig`
  - [x] `Block/featuredUser.html.twig`
- [x] Reenable avatar editing
  - [x] Update `Zikula.Profile.Avatar.js`
- [x] Add functionality for uploading custom avatar images
  - [x] A modvar should control whether upload functionality is allowed/activated or not.
  - [x] Further settings allow to define maximum size/width/height and whether too large images should be shrinked
  - [x] Deprecate https://github.com/zikula-ev/Avatar
- [x] Update vendors of core to include newest Profile revision
- [x] Update generator, too

**Comment by craigh** [comment]
@Guite maybe you can look into this?

**Comment by Guite** [comment]
Places to be looked at (using the old Smarty avatar plugin) as part of this (after merging #3610):

- system/UsersModule/Controller/LiveSearchController.php
- system/UsersModule/Twig/Extension/ProfileExtension.php
