### ISSUE TITLE
Fields do not seam searchable

### ISSUE THREAD

**Issue by craigh** [zikula-modules/Profile#82]
If I try to search for a value I know exists in the 'real name' field, the result is not returned.

**Comment by craigh** [comment]
I don't think Searchable is implemented at all.

![screen shot 2017-07-22 at 8 23 57 am](https://user-images.githubusercontent.com/350048/28491056-35c112c4-6eb7-11e7-8a22-5acccc21980c.png)

**Comment by Guite** [comment]
Fix in https://github.com/zikula/core/pull/3699

**Comment by craigh** [comment]
This will be postponed then.
