### ISSUE TITLE
Avatar can not be uploaded

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Profile#86]
This is the setting in profile:
![grafik](https://user-images.githubusercontent.com/935250/28537748-428f139c-70ac-11e7-84dc-a49be50529a9.png)
And this is what a user in the group Users is able to do:
![grafik](https://user-images.githubusercontent.com/935250/28537792-5c7f1180-70ac-11e7-8de0-5260b8770ab4.png)
No selection or upload of an Avatar

**Comment by Guite** [comment]
Please post a screenshot of your properties list.

**Comment by rallek** [comment]
![grafik](https://user-images.githubusercontent.com/935250/28540051-3b9ffe2c-70b4-11e7-9715-c3f9ddd43d1e.png)

**Comment by Guite** [comment]
Did you try to set the `avatar` field to Active?

**Comment by rallek** [comment]
Ups. That simple...

**Comment by craigh** [comment]
why are they all inactive though I wonder

**Comment by craigh** [comment]
https://github.com/zikula-modules/Profile/blob/master/Helper/UpgradeHelper.php#L100

indicates they should have maintained their active status on upgrade. Is that what happened Ralf?

**Comment by rallek** [comment]
In 1.4.6 I deactivated all but realname. When I yesterday activated the Avatar I struggelt first about the 0. I made it a 2.
