### ISSUE TITLE
proper gravatar image not displayed in edit mode

### ISSUE THREAD

**Issue by craigh** [zikula-modules/Profile#87]
I think this is trying to display the proper image but failing. a valid value is set previously (as the real acct email) and visible on the profile page, so it should be displayed here too.

![screen shot 2017-07-30 at 8 20 55 am](https://user-images.githubusercontent.com/350048/28753271-1d44465e-7500-11e7-88f3-222ea3d74ab6.png)

**Comment by Guite** [comment]
It is intentionally displaying a placeholder only instead of the actual image at the moment. Displaying the real image instead is a feature request.

**Comment by Guite** [comment]
![Screenshot_20200106_152209](https://user-images.githubusercontent.com/277531/71823767-59531200-3098-11ea-86f3-09b3c5064421.png)
