### ISSUE TITLE
Event 'module.profile.dud_item_modify' no longer exists

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Profile#88]
The event`module.profile.dud_item_modify` no longer exists. Is there a replacement?

**Comment by craigh** [comment]
`module.profile.dud_item_modify` was an _event_, not a _listener_

refs: https://github.com/zikula-modules/Profile/commit/40d4a9db634bda561992ee6846476606e5b2414c

there is no direct replacement.
I think the best way to replace this behavior would be to create your own FormType and add it to the property list by listening to the event fired here: https://github.com/zikula-modules/Profile/blob/master/Form/Type/PropertyType.php#L233

Within that form type you can add your own logic for filtering and manipulate the form as required.

**Comment by shefik** [comment]
@craigh Is it even possible to change the form via the current code?

Firstly, `Zikula\ProfileModule\FormTypesChoices` is set as `private`, so the array can't be changed. Secondly, the event returns the `choices` array within the `subject`. There is no `$event->setSubject()`.

**Comment by craigh** [comment]
> I think the best way to replace this behavior would be to **create your own FormType**

you shouldn't be manipulating other form types. create your own. with your own choices. Add the new form type to the choices available using the event.

**Comment by craigh** [comment]
> Is it even possible to change the form via the current code?

I never tried but I assumed so. perhaps the code isn't working as I intended as your concerns would imply. 
I think you should be able to change the choices by doing something like

```
$choices = $event->getSubject();
$choices['Custom Field'] = CustomType::class;
```

an object shouldn't require you to set the subject again.

**Comment by shefik** [comment]
I'll try again.

**Comment by shefik** [comment]
I have it working via the function `$args['subject']->offsetSet()`.
