### ISSUE TITLE
Issue with textType

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/Profile#93]
- [ ] the field is not shown, calling the form for creating a new property -> Regex validation string constraint
- [ ] get error with trying to edit a textType field:  An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class Symfony\Component\Validator\Constraints\Regex could not be converted to string") in "ZikulaFormExtensionBundle:Form:bootstrap_3_zikula_admin_layout.html.twig".```

**Comment by rallek** [comment]
I can reproduce.

Profile 3.0.3 / Zikula 1.5.3 / Symfony 2.8.28 / PHP 5.6.32-nmm1

**Comment by Guite** [comment]
Fixed in https://github.com/zikula/core/compare/d6764ba8bb7037275b0753686b9a66480887a604...ee4e3e52adb787b5056596b4bd7c582ec177d2fd
